package com.system.SchoolManagementSystem.termmanagement.repository;

import com.system.SchoolManagementSystem.termmanagement.entity.TermFeeItem;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;

@Repository
public interface TermFeeItemRepository extends JpaRepository<TermFeeItem, Long> {

    List<TermFeeItem> findByStudentTermAssignmentId(Long studentTermAssignmentId);

    List<TermFeeItem> findByStudentTermAssignmentStudentId(Long studentId);

    List<TermFeeItem> findByStatus(TermFeeItem.FeeStatus status);

    List<TermFeeItem> findByDueDateBeforeAndStatus(LocalDate date, TermFeeItem.FeeStatus status);

    @Query("SELECT t FROM TermFeeItem t WHERE t.studentTermAssignment.student.id = :studentId AND t.status IN ('PENDING', 'PARTIAL', 'OVERDUE') ORDER BY t.dueDate, t.sequenceOrder")
    List<TermFeeItem> findUnpaidItemsByStudentOrdered(@Param("studentId") Long studentId);

    @Query("SELECT t FROM TermFeeItem t WHERE t.studentTermAssignment.student.id = :studentId AND t.studentTermAssignment.academicTerm.id = :termId")
    List<TermFeeItem> findByStudentAndTerm(@Param("studentId") Long studentId, @Param("termId") Long termId);

    @Query("SELECT t FROM TermFeeItem t WHERE t.studentTermAssignment.academicTerm.id = :termId AND t.itemType = 'ADDITIONAL'")
    List<TermFeeItem> findAdditionalFeesForTerm(@Param("termId") Long termId);

    @Query("SELECT t FROM TermFeeItem t WHERE t.studentTermAssignment.student.id = :studentId AND t.itemType = 'ADDITIONAL'")
    List<TermFeeItem> findAdditionalFeesForStudent(@Param("studentId") Long studentId);

    @Query("SELECT t FROM TermFeeItem t WHERE t.studentTermAssignment.student.id = :studentId AND t.isAutoGenerated = false")
    List<TermFeeItem> findManualFeesForStudent(@Param("studentId") Long studentId);

    @Query("SELECT COALESCE(SUM(t.amount), 0) FROM TermFeeItem t WHERE t.studentTermAssignment.academicTerm.id = :termId AND t.feeType = :feeType")
    Double getTotalByFeeTypeForTerm(@Param("termId") Long termId, @Param("feeType") TermFeeItem.FeeType feeType);

    @Query("SELECT t.feeType, SUM(t.amount) as total FROM TermFeeItem t WHERE t.studentTermAssignment.academicTerm.id = :termId GROUP BY t.feeType")
    List<Object[]> getFeeBreakdownByTypeForTerm(@Param("termId") Long termId);

    @Query("SELECT t FROM TermFeeItem t WHERE t.dueDate BETWEEN :startDate AND :endDate AND t.status IN ('PENDING', 'OVERDUE')")
    List<TermFeeItem> findItemsDueBetween(@Param("startDate") LocalDate startDate,
                                          @Param("endDate") LocalDate endDate);

    @Query("SELECT t FROM TermFeeItem t WHERE t.studentTermAssignment.student.id = :studentId AND t.status IN ('PENDING', 'PARTIAL') ORDER BY t.sequenceOrder ASC, t.dueDate ASC")
    List<TermFeeItem> findPendingItemsOrderedBySequence(@Param("studentId") Long studentId);

    @Query("SELECT t FROM TermFeeItem t WHERE t.studentTermAssignment.student.id = :studentId AND t.status = 'OVERDUE' ORDER BY t.dueDate ASC")
    List<TermFeeItem> findOverdueItemsForStudent(@Param("studentId") Long studentId);
}