-- ===========================================
-- Tenant Database Schema v1.0
-- Auto-generated by School Management System
-- ===========================================

-- Students Table
CREATE TABLE IF NOT EXISTS students (
    id BIGINT NOT NULL AUTO_INCREMENT,
    academic_year VARCHAR(10) NOT NULL,
    address VARCHAR(255),
    admission_date DATE NOT NULL,
    blood_group ENUM('AB_MINUS','AB_PLUS','A_MINUS','A_PLUS','B_MINUS','B_PLUS','O_MINUS','O_PLUS','UNKNOWN'),
    blood_pressure VARCHAR(20),
    bus_number VARCHAR(20),
    bus_route VARCHAR(50),
    bus_stop VARCHAR(100),
    category ENUM('GENERAL','OBC','OTHER','SC','ST'),
    class_teacher VARCHAR(100),
    clinic_name VARCHAR(100),
    created_at DATETIME(6),
    date_of_birth DATE NOT NULL,
    doctor_name VARCHAR(100),
    driver_contact VARCHAR(20),
    driver_name VARCHAR(100),
    drop_time VARCHAR(255),
    email VARCHAR(255),
    emergency_contact_name VARCHAR(100),
    emergency_contact_phone VARCHAR(20),
    emergency_relation VARCHAR(50),
    full_name VARCHAR(100) NOT NULL,
    gender ENUM('FEMALE','MALE','OTHER') NOT NULL,
    grade VARCHAR(20) NOT NULL,
    height VARCHAR(255),
    house VARCHAR(255),
    last_medical_checkup DATE,
    nationality VARCHAR(255),
    phone VARCHAR(255),
    pickup_time VARCHAR(255),
    profile_picture VARCHAR(255),
    religion VARCHAR(255),
    roll_number VARCHAR(20),
    status ENUM('ACTIVE','GRADUATED','INACTIVE','TRANSFERRED'),
    student_id VARCHAR(20) NOT NULL,
    transport_fee DOUBLE,
    transport_fee_status ENUM('OVERDUE','PAID','PENDING'),
    transport_mode ENUM('OTHER','PRIVATE_VEHICLE','PUBLIC_TRANSPORT','SCHOOL_BUS','WALKING'),
    updated_at DATETIME(6),
    weight VARCHAR(255),
    PRIMARY KEY (id),
    UNIQUE KEY uk_student_id (student_id),
    INDEX idx_student_grade (grade),
    INDEX idx_student_academic_year (academic_year),
    INDEX idx_student_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Family Members Table
CREATE TABLE IF NOT EXISTS family_members (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6),
    email VARCHAR(255),
    full_name VARCHAR(100) NOT NULL,
    is_emergency_contact BIT,
    is_primary_contact BIT,
    occupation VARCHAR(255),
    phone VARCHAR(255),
    relation ENUM('FATHER','GUARDIAN','MOTHER','OTHER','SIBLING') NOT NULL,
    updated_at DATETIME(6),
    student_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_family_members_student FOREIGN KEY (student_id)
        REFERENCES students (id) ON DELETE CASCADE,
    INDEX idx_family_student (student_id),
    INDEX idx_family_relation (relation)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Medical Records Table
CREATE TABLE IF NOT EXISTS medical_records (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6),
    frequency VARCHAR(255),
    name VARCHAR(100) NOT NULL,
    notes VARCHAR(255),
    prescribed_by VARCHAR(100),
    record_type ENUM('ALLERGY','CONDITION','MEDICATION') NOT NULL,
    severity ENUM('CRITICAL','MILD','MODERATE','SEVERE'),
    updated_at DATETIME(6),
    student_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_medical_records_student FOREIGN KEY (student_id)
        REFERENCES students (id) ON DELETE CASCADE,
    INDEX idx_medical_student (student_id),
    INDEX idx_medical_type (record_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Achievements Table
CREATE TABLE IF NOT EXISTS achievements (
    id BIGINT NOT NULL AUTO_INCREMENT,
    award VARCHAR(255),
    certificate_path VARCHAR(255),
    created_at DATETIME(6),
    description TEXT,
    level ENUM('DISTRICT','INTERNATIONAL','NATIONAL','SCHOOL','STATE') NOT NULL,
    title VARCHAR(200) NOT NULL,
    type ENUM('ACADEMIC','ARTS','CULTURAL','LEADERSHIP','OTHER','SPORTS') NOT NULL,
    updated_at DATETIME(6),
    verified_at DATETIME(6),
    verified_by VARCHAR(255),
    year INTEGER NOT NULL,
    student_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_achievements_student FOREIGN KEY (student_id)
        REFERENCES students (id) ON DELETE CASCADE,
    INDEX idx_achievement_student (student_id),
    INDEX idx_achievement_type (type),
    INDEX idx_achievement_year (year)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Student Interests Table
CREATE TABLE IF NOT EXISTS student_interests (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6),
    description TEXT,
    interest_type ENUM('CLUB','HOBBY') NOT NULL,
    name VARCHAR(100) NOT NULL,
    student_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_student_interests_student FOREIGN KEY (student_id)
        REFERENCES students (id) ON DELETE CASCADE,
    INDEX idx_interest_student (student_id),
    INDEX idx_interest_type (interest_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Users Table (for tenant-specific authentication)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    tenant_id VARCHAR(50) NOT NULL,
    database_name VARCHAR(50),
    full_name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(20),
    is_enabled BOOLEAN DEFAULT true,
    account_non_expired BOOLEAN DEFAULT true,
    account_non_locked BOOLEAN DEFAULT true,
    credentials_non_expired BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_username_tenant (username, tenant_id),
    INDEX idx_tenant_id (tenant_id),
    INDEX idx_role (role),
    UNIQUE KEY uk_username_tenant (username, tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===========================================
-- Additional Tenant-specific Tables
-- ===========================================

-- Demo Entities Table (if needed)
CREATE TABLE IF NOT EXISTS demo_entities (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    value INT,
    is_active BOOLEAN DEFAULT true,
    category VARCHAR(50),
    tenant_id VARCHAR(50) NOT NULL,
    created_by VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_tenant_id (tenant_id),
    INDEX idx_category (category),
    INDEX idx_is_active (is_active),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ===========================================
-- Insert Default Data (Optional)
-- ===========================================

-- INSERT INTO users (username, password, role, tenant_id, is_enabled)
-- VALUES ('admin', '$2a$10$YourHashedPasswordHere', 'ADMIN', '{{TENANT_ID}}', true);