package com.system.SchoolManagementSystem.termmanagement.dto.response;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import java.time.LocalDate;
import java.util.List;

@Data
public class StudentFeeDetailsResponse {

    private Long studentId;
    private String studentName;
    private String studentCode;
    private String grade;
    private String className;

    // Current term summary
    private Long currentTermId;
    private String currentTermName;
    private String academicYear;

    // Overall fee summary
    private Double totalFee;
    private Double paidAmount;
    private Double pendingAmount;
    private String feeStatus;
    private Double paymentPercentage;

    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate feeDueDate;

    // Term-wise breakdown
    private List<TermFeeSummary> termSummaries;

    // Detailed fee items for current term
    private List<TermFeeItemResponse> feeItems;

    // Payment history summary
    private PaymentSummary paymentSummary;

    // Parent/Guardian information
    private GuardianInfo guardianInfo;

    // Reminder information
    private ReminderInfo reminderInfo;

    @Data
    public static class TermFeeSummary {
        private Long termId;
        private String termName;
        private Double totalFee;
        private Double paidAmount;
        private Double pendingAmount;
        private String status;

        @JsonFormat(pattern = "yyyy-MM-dd")
        private LocalDate dueDate;

        private Boolean isCurrent;
    }

    @Data
    public static class TermFeeItemResponse {
        private Long id;
        private String itemName;
        private String feeType;
        private String itemType; // BASIC, ADDITIONAL, DISCOUNT, etc.
        private Double amount;
        private Double paidAmount;
        private Double pendingAmount;
        private String status;

        @JsonFormat(pattern = "yyyy-MM-dd")
        private LocalDate dueDate;

        @JsonFormat(pattern = "yyyy-MM-dd")
        private LocalDate billingDate;

        private Boolean isAutoGenerated;
        private Boolean isMandatory;
        private Integer sequenceOrder;
        private String notes;
    }

    @Data
    public static class PaymentSummary {
        private Integer totalPayments;
        private Double totalAmountPaid;

        @JsonFormat(pattern = "yyyy-MM-dd")
        private LocalDate lastPaymentDate;

        private String lastPaymentMethod;
        private Double lastPaymentAmount;
        private String lastPaymentReference;
    }

    @Data
    public static class GuardianInfo {
        private String guardianName;
        private String relationship;
        private String phoneNumber;
        private String email;
        private String address;
    }

    @Data
    public static class ReminderInfo {
        private Integer remindersSent;

        @JsonFormat(pattern = "yyyy-MM-dd")
        private LocalDate lastReminderDate;

        private String lastReminderType;
        private Integer overdueDays;
    }
}